version: '3.9'

services:
  # saimonverdin-backend:
  #   container_name: saimonverdin-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: saimonverdin-backend:1.0
  #   ports:
  #     - '5016:5016'
  #   restart: unless-stopped
  redis:
    image: redis:7.2 # Use latest stable Redis
    container_name: redis-server
    ports:
      - '6379:6379' # Expose Redis on localhost:6379
    restart: unless-stopped
